### PR TITLE
Fix cesm restarting: 

### LINKED ISSUE #377: Exact restart tests are failing
The following Exact restart tests are failing in comparing the restart history files to the simulation of a continuous run.

```
ERS.f09_f09_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  COMPARE_base_rest 		
ERS.f19_f19_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default	  COMPARE_base_rest 		
ERS.f19_f19_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  COMPARE_base_rest 		
ERS.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  COMPARE_base_rest 		
ERS.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default	  COMPARE_base_rest 		
ERS.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  COMPARE_base_rest 		
ERS.nldas2_nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default	  COMPARE_base_rest 		
ERS.nldas2_nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  COMPARE_base_rest 
```

### PR DESCRIPTION
**Pull request by nmizukami**
For CESM coupling mode, restart information is not quite set (for `rtmCTL`). This affect all negative runoff handling (irrigation and qgwl). 

Initialize some `rtmCTL` variables (river volume-`rtmCTL%volr` and also river discharge-`rtmCTL%discharge`) from restart file.

Use isRestart global variable (newly created) instead of using `fname_restart_in` to detect restart run.

Fixed one history output variable (volume) initialization from restart file.

Additional fix:  Right now, precipitation and evaporation are not passed from coupler and mizuRoute assume they are zero. So need to initialize precipitation and evaporation array with zero (gnu compiler put large values). 

Fixes #377

### CODE REVIEW

**Review by ekluzek — CHANGES_REQUESTED** [review]
To review what we just discussed. We need the if section about the isRestart flag for the control file to be done for the standalone case, but not for coupled. So coupled will set isRestart based on nsrest settings.

File: route/build/cpl/RtmMod.F90 [hunk 1]
```diff
@@ -249,6 +253,7 @@ SUBROUTINE route_ini(rof_active,flood_active)
     if ((nsrest == nsrContinue) .or. &
         (nsrest == nsrBranch)) then
       call RtmRestGetfile()
+      isRestart=.true.
```
Comment (ekluzek) [inline route/build/cpl/RtmMod.F90:256]: Add a else statement to set this to false for the else condition.

File: route/build/src/read_control.f90 [hunk 2]
```diff
@@ -342,6 +344,13 @@ SUBROUTINE read_control(ctl_fname, err, message)
    restart_dir = output_dir
  endif
 
+ ! ---------- restart option  ---------------------------------------------------------------------
```
Comment (ekluzek) [inline route/build/src/read_control.f90:347]: Make sure this only happens for standalone.

Comment (ekluzek) [reply route/build/src/read_control.f90:347]: Or it could be done, but we ignore it for the coupled case?

Comment (ekluzek) [reply route/build/src/read_control.f90:347]: This can be done by setting runMode earlier in rof_comp_nuopc, so it can be accessed at this point.

Comment (nmizukami) [reply route/build/src/read_control.f90:348]: Added if statement to set isRestart only if `runMode` is standalone

File: route/build/cpl/RtmMod.F90 (hunk 1 above)
Comment (nmizukami) [reply route/build/cpl/RtmMod.F90:253]: Added else statement and isRestart is set to false

File: route/build/cpl/RtmMod.F90 [hunk 3]
```diff
@@ -27,6 +27,7 @@ MODULE RtmMod
   USE globalData,   ONLY: npes       => nNodes
   USE globalData,   ONLY: mpicom_rof => mpicom_route
   USE globalData,   ONLY: masterproc
+  USE globalData,   ONLY: isColdStart                ! restart flag
```
Comment (ekluzek) [inline route/build/cpl/RtmMod.F90:30]: I suggest changing the comment here...

File: route/build/cpl/RtmMod.F90 [hunk 4]
```diff
@@ -246,13 +247,13 @@ SUBROUTINE route_ini(rof_active,flood_active)
...
+    if ((nsrest == nsrContinue) then
       call RtmRestGetfile()
-      if (nsrest == nsrContinue) then
-        call init_histFile(ierr, cmessage)
-        if(ierr/=0)then; call shr_sys_abort(trim(subname)//trim(cmessage)); endif
-      end if
+      isColdStart=.false.
+      call init_histFile(ierr, cmessage)
+      if(ierr/=0)then; call shr_sys_abort(trim(subname)//trim(cmessage)); endif
+    else
```
Comment (ekluzek) [inline route/build/cpl/RtmMod.F90:255]: Actually in this case now, we should listen to what's on the control file and use what it's saying...

File: route/build/src/init_model_data.f90 [hunk 5]
```diff
@@ -325,6 +325,7 @@ SUBROUTINE init_state_data(pid, nNodes, comm, ierr, message)
   USE globalData, ONLY: nMolecule              ! computational molecule
   USE globalData, ONLY: TSEC                   ! begining/ending of simulation time step [sec]
   USE globalData, ONLY: initHvars              ! status of history variabiable data initialization
+  USE globalData, ONLY: isColdStart            ! restart flag
```
Comment (ekluzek) [inline route/build/src/init_model_data.f90:328]: Change the comment...

File: route/build/src/read_control.f90 [hunk 6]
```diff
@@ -28,11 +28,13 @@ SUBROUTINE read_control(ctl_fname, err, message)
  USE globalData, ONLY: meta_PFAF               ! pfafstetter code
  USE globalData, ONLY: meta_rflx               ! river flux variables
  USE globalData, ONLY: meta_hflx               ! river flux variables
+ USE globalData, ONLY: isColdStart             ! number of active routing methods
```
Comment (ekluzek) [inline route/build/src/read_control.f90:31]: Comment needs to be updated...

**Review by ekluzek — APPROVED** [review]
One important change I ask for here to make sure you listen to the control file when continue_run is FALSE. And just a couple notes about updating the comments about the isColdStart flag...

Approving just to make it easier...

File: route/build/cpl/RtmMod.F90 (hunk 4 above)
Comment (nmizukami) [reply route/build/cpl/RtmMod.F90:255]: So should I change if statement from `if (nsrest == nsrContinue) then` to `if (continue_run) then`? 

if i change now, it won't work because there is no mechanism to change continue_run in control file right now, so wait till this mechanism is implemented (in Buildnml?)

File: route/build/src/init_model_data.f90 (hunk 5 above)
Comment (nmizukami) [reply route/build/src/init_model_data.f90]: comment updated

File: route/build/src/read_control.f90 (hunk 6 above)
Comment (nmizukami) [reply route/build/src/read_control.f90]: comment updated

File: route/build/cpl/RtmMod.F90 (hunk 3 above)
Comment (nmizukami) [reply route/build/cpl/RtmMod.F90]: comment updated

File: route/build/cpl/RtmMod.F90 (hunk 4 above)
Comment (ekluzek) [reply route/build/cpl/RtmMod.F90:255]: I would leave the if statement as

`if (nsrest == nsrContinue) then`

as you point out we can't change it until the buildnml change happens. And even then you might as well leave it as above, there isn't enough of a reason to change it.

Comment (ekluzek) [reply route/build/cpl/RtmMod.F90:255]: My point was actually to now remove the

``` fortran
else
   isColdStart = .true.
```

because now we want that to set by the control file if it isn't a nsrContinue case.

Comment (nmizukami) [reply route/build/cpl/RtmMod.F90]: ok. I removed those two lines.
