### PR TITLE
Some fixes so can run on izumi

### LINKED ISSUE #259: Change MODEL to COMP_NAME
In a recent version of cime, components need to change the use of MODEL in buildlib to COMP_NAME. I'm finding this a problem with building and running on izumi.

### LINKED ISSUE #266: Add list of files needed to be read in to mizuroute.input_data_list
In the buildnml we need to add the list of files that mizuRoute is going to read to the file: for.input_data_list.  Currently we've been relying on those files already being in place for mizuRoute to work. Adding this will allow cime to download them before the run is done. I noticed this starting to work on izumi, since it wasn't automatically downling the needed files.

### LINKED ISSUE #270: A blank line in the user_ctl_mizuroute file gives a hard to decipher error
A blank line in the user_ctl_mizuroute file gives the following hard to dechiper error:

> ERROR: Error in reading in line:
>

The fix is just to remove the blank line. But, we should make it more obvious what is going wrong and how the user might fix it.

### LINKED ISSUE #275: Trouble building with the nag compiler on izumi
I'm running into some trouble building with the nag compiler on izumi. There is a I/O descriptor that needs to be changed, and there are lines longer than 132 characters that should be shortened.

Here's the output of the build:

> NAG Fortran Compiler Release 6.2(Chiyoda) Build 6207
> Option warning: The -mismatch option disables the -C=calls option
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 109: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 110: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 111: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 112: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 113: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 114: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 115: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 116: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 118: Line longer than 132 characters
> Extension: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 119: Line longer than 132 characters - further long line messages suppressed
> Warning: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 410: NVARSRFLX explicitly imported into READ_CONTROL but not used
> Time(Parsing): User 0.16, System 1.94
> Error: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/read_control.f90, line 97: No spacing specified for X edit descriptor
> Time(Semantic Analysis): User 0.00, System 0.00

### LINKED ISSUE #276: Change use of "isnan" to cime share code shr_infnan_isnan
isnan is an intrinsic function only available on certain compilers. So to make this more general we need to make sure of the cime share code shr_infnan_isnan that does this for all CESM supported compilers.

There's a use of isnan in 

route/build/src/mc_route.f90

### LINKED ISSUE #277: nag runtime issues
After dealing with #275 and #276 in order to build, I ran into the following issues at runtime for the NAG compiler.

For the test: ERS_D.5x5_amazon_rHDMA.I2000Clm50SpMizGs.izumi_nag.mizuroute-default

cesm.log gives:

```
[0] (shr_orb_params) -----------------------------------------
[1] 
[2] 
[3] 
[4] 
[5] 
[6] 
[7] 
[8] 
[9] 
[10] 
[11] 
[12] 
[13] 
[14] 
[15] 
[16] 
[17] 
[18] 
[19] 
[20] 
[21] 
[22] 
[23] 
[24] 
[0] Runtime Error: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90, line 209: Dangling pointer LIST used as argument[2] Runtime Error: [3] Runtime Error: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90, line 209: Dangling pointer LIST used as argument to intrinsic function ASSOCIATED
[3] Target was DEALLOCATEd at[10] Runtime Error: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90, line 209: Dangling pointer LIST used as argument to intrinsic function ASSOCIATED
[10] Target was DEALLOCATEd at li[13] Runtime Error: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90, line 209: Dangling pointer LIST used as argument to intrinsic function ASSOCIATED
[13] Target was DEALLOCATEd at line 207 of /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90
[16] Runtime Error: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90, line 209: Dangling pointer LIST used as argument to intrinsic function ASSOCIATED
[16] Target was DEALLOCATEd at line 207 of /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90
[16] Program terminated by fatal error
[16] /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90, line 209: Error occurred in ASCII_UTIL_MODULE:GET_VLINES
[18] Runtime Error: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/ascii_util.f90, line 209: Dangling pointer LIST used as argument to intrinsic function ASSOCIATED
```

### LINKED ISSUE #397: NAG compiler complains when swap function is called on identical inputs
The NAG compiler on izumi complains about the following in nr_utils.f90

``` fortran
 ! private subroutine
 SUBROUTINE swap(a,b)
 INTEGER(I4B), INTENT(INOUT) :: a,b
 INTEGER(I4B) :: dum
 dum=a
 a=b
 b=dum
 END SUBROUTINE swap
```
It complains about the change in a dummy argument changing another dummy argument at the same time.

There must be some way to override this protection or maybe there is an intrinsic that does this same thing?

> Completion(send) Runtime Error: /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/nr_utils.f90, line 163: Assignment to A affects dummy argument B
> Program terminated by fatal error
> /fs/cgd/data0

### LINKED ISSUE #399: PIO free decomp should not be done each time the file is closed...
Running with NAG I get the following error for a dangling pointing when the freedecomp is being called from close_all for closing the NetCDF history files.

In this case the test that I'm doing is:

SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default

> Runtime Error: /fs/cgd/data0/erik/ctsm_worktree/mizuroute/libraries/parallelio/src/flib/piolib_mod.F90, line 1421: Reference to dangling pointer FILE%IOSYSTEM
> Target was RETURNed from procedure PIOLIB_MOD:PIO_OPENFILE
> Program terminated by fatal error
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/libraries/parallelio/src/flib/piolib_mod.F90, line 1421: Error occurred in PIOLIB_MOD:FREEDECOMP_FILE
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/pio_utils.f90, line 366: Called by PIO_UTILS:FREEDECOMP
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/historyFile.f90, line 406: Called by HISTORYFILE:CLEANUP_HRU
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/historyFile.f90, line 391: Called by HISTORYFILE:CLEANUP
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/write_simoutput_pio.f90, line 456: Called by WRITE_SIMOUTPUT_PIO:CLOSE_ALL
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/write_simoutput_pio.f90, line 69: Called by WRITE_SIMOUTPUT_PIO:MAIN_NEW_FILE
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/cpl/RtmMod.F90, line 429: Called by RTMMOD:ROUTE_RUN
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/cpl/nuopc/rof_comp_nuopc.F90, line 793: Called by ROF_COMP_NUOPC:MODELADVANCE

I thought the first problem was that HistFile%fileStatus wasn't being explicitly set to FALSE. It is in the type declaration, but I wondered if that was always the case. However, simply making sure it's set to FALSE, doesn't fix the problem.

However, not doing the freedecomp each time the file is closed, does allow the test to work.

### LINKED ISSUE #406: ERP tests failing to run
Exact restart tests with a change in threadcount are failing to run. It fails on opening the restart file on

ERP_D_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default

Other compilers fail as well. ERS tests work. And ERP tests without mizuRoute work as well.

### LINKED ISSUE #411: RUN_REFCASE branch cases seem to start back at START_TIME rather than RUN_REFDATE, causes ERI tests to fail
ERI cases are failing with errors in the comparison for hybrid or branch steps.

For example...

FAIL ERI_Ld12_PS.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default COMPARE_base_hybrid
FAIL ERI_Ld12_PS.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default COMPARE_base_rest

It looks like the branch case for mizuRoute history files goes back to the RUN_STARTDATE, but other components such as CLM startup at RUN_REFDATE.

### PR DESCRIPTION
**Pull request by ekluzek**
Some fixes so will compile and run on izumi, with nag compiler. Fix several small issues. Get the list of input files working. Have the PIO decomp free only done after the file is freed. Get ERP and ERI tests to work. 

Fixes #277
Fixes #275
Fixes #266
Fixes #270
Fixes #276
Fixes #397
Fixes #399
Fixes #259
Fixes #406
Fixes #411

### CODE REVIEW

File: route/build/src/init_model_data.f90 [hunk 1]
```diff
@@ -587,7 +588,8 @@ SUBROUTINE init_ntopo(nHRU_out, nRch_out,
     !        --> users can modify the hard-coded parameter "maxUpstreamFile" if desired
     if(tot_upstream > maxUpstreamFile) tot_upstream=0
 
-    call system('rm -f '//trim(ancil_dir)//trim(fname_ntopNew))
+    call shr_sys_system('rm -f '//trim(ancil_dir)//trim(fname_ntopNew), ierr)
```
Comment (ekluzek) [inline route/build/src/init_model_data.f90:591]: In order to run on all systems the shr_sys_system and shr_sys_flush and shr_infnan_isnan needs to be used from the CESM share code. The one issue with this is to ensure it still works with the standalone build.

File: route/build/src/mpi_utils.f90 [hunk 2]
```diff
@@ -975,7 +976,7 @@ SUBROUTINE shr_mpi_abort(message, ierr, comm)
     integer(i4b)                :: jerr
 
     write(iulog,*) trim(subName),trim(message),ierr
-    call flush(6)
+    call shr_sys_flush(6)
```
Comment (ekluzek) [inline route/build/src/mpi_utils.f90:979]: shr_sys_flush usage...

File: route/build/src/water_balance.f90 [hunk 3]
```diff
@@ -200,7 +201,7 @@ SUBROUTINE comp_global_wb(ixRoute, verbose, ierr, message)
     if (abs(wb_error) > 1._dp) then ! tolerance is 1 [m3]
       write(iulog,'(A,1PG15.7,1X,A)') ' WARNING: global WB error [m3] = ', wb_error, '> 1.0 [m3]'
     end if
-    flush(iulog)
+    call shr_sys_flush(iulog)
```
Comment (ekluzek) [inline route/build/src/water_balance.f90:204]: shr_sys_flush

Comment (ekluzek) [reply route/build/src/water_balance.f90:204]: Talking with @nmizukami maybe the best solution would be to remove this flush statement.

File: route/build/src/mpi_utils.f90 (hunk 2 above)
Comment (ekluzek) [reply route/build/src/mpi_utils.f90:979]: Talking with @nmizukami maybe the best solution would be to remove this flush statement.

File: route/build/src/init_model_data.f90 (hunk 1 above)
Comment (ekluzek) [reply route/build/src/init_model_data.f90:591]: MAybe this isn't needed. You can probably overwrite the file on the open.

Comment (ekluzek) [reply route/build/src/init_model_data.f90:591]: We will do the same for the isnan check as well -- just remove it.

File: route/build/src/water_balance.f90 (hunk 3 above)
Comment (ekluzek) [reply route/build/src/water_balance.f90]: I'm changing all the shr_sys_flush calls to the 2003 FORTRAN flush keyword.

File: route/build/src/mpi_utils.f90 (hunk 2 above)
Comment (ekluzek) [reply route/build/src/mpi_utils.f90]: I've changed the flush statements in the shared src directory so they are in the FORTRAN 2003 keyword form:

flush(unit)

File: route/build/src/init_model_data.f90 (hunk 1 above)
Comment (ekluzek) [reply route/build/src/init_model_data.f90]: I commented out the isnan check, and add some discussion about it.

**Comment by ekluzek** [comment]
The ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default is showing different answers for the base to restart:

> grep RMS /scratch/cluster/erik/tests_ctsm51d114mizum/ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default.GC.ctsm51d114mizum_nag/run/ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default.GC.ctsm51d114mizum_nag.clm2.h0.2000-01-12-00000.nc.base.cprnc.out
>  RMS TWS                              7.2598E+00            NORMALIZED  2.7414E-03
>  RMS VOLR                             6.8603E+08            NORMALIZED  9.3896E-01
>  RMS VOLRMCH                          6.8603E+08            NORMALIZED  9.3896E-01
> (ctsm_py) [erik@izumi ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default.GC.ctsm51d114mizum_nag]$ grep RMS /scratch/cluster/erik/tests_ctsm51d114mizum/ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default.GC.ctsm51d114mizum_nag/run/ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default.GC.ctsm51d114mizum_nag.mizuroute.h.2000-01-12-00000.nc.base.cprnc.out

 RMS IRFroutedRunoff                  8.1284E+02            NORMALIZED  1.2922E+00
(ctsm_py) [erik@izumi ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default.GC.ctsm51d114mizum_nag]$ grep RMS  /scratch/cluster/erik/tests_ctsm51d114mizum/ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default.GC.ctsm51d114mizum_nag/run/ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default.GC.ctsm51d114mizum_nag.mizuroute.h.2000-01-12-00000.nc.base.cprnc.out
 RMS IRFroutedRunoff                  8.1284E+02            NORMALIZED  1.2922E+00

File: route/build/src/ascii_utils.f90 [hunk 4]
```diff
@@ -204,8 +204,10 @@ SUBROUTINE get_vlines(unt,vlines,err,message)
   vlines(current%ix) = current%chardat
   previous=>current; current=>current%next
   deallocate(previous)
+  nullify(previous)
  end do
- if(associated(list)) nullify(list)
+ nullify(list)
+ !if(associated(list)) nullify(list)
```
Comment (ekluzek) [inline route/build/src/ascii_utils.f90:210]: Just remove the commented out line.

**Review by ekluzek — COMMENTED** [review]
@nmizukami and I went over this. I'm going to do some work to see if I really have to comment out the calls to the free subroutines. If I do need it maybe I can set it up, so that it only applies for the Nag compiler.

His abstract class PR should come in first, and then this one. So it won't be merged until after that one.

File: cime_config/buildnml [hunk 5]
```diff
@@ -322,12 +321,15 @@ def buildnml(case, caseroot, compname):
     create_namelist_infile(case, user_nl_file, infile)
     control_infile = [infile]
 
+    # NOTE: User definition *replaces* existing definition.
+    files = Files(comp_interface="nuopc")
+
     # Create the namelist generator object - independent of instance
-    definition_files = [srcroot + "/cime_config/namelist_definition_mizuRoute.xml"]
-    nmlgen = NamelistGenerator(case, definition_files)
+    definition_files = [os.path.join( srcroot,  "cime_config/namelist_definition_mizuRoute.xml") ]
```
Comment (nmizukami) [inline cime_config/buildnml:328]: Just curious----
to form file path,  using `os.path join` is better than a simple string concatenation?

File: route/build/src/ascii_utils.f90 (hunk 4 above)
Comment (nmizukami) [reply route/build/src/ascii_utils.f90:210]: Yes,  I think this can be safely removed

File: route/build/src/mpi_utils.f90 [hunk 6]
```diff
@@ -975,7 +975,7 @@ SUBROUTINE shr_mpi_abort(message, ierr, comm)
     integer(i4b)                :: jerr
 
     write(iulog,*) trim(subName),trim(message)
-    call flush(6)
+    flush(6)
```
Comment (nmizukami) [inline route/build/src/mpi_utils.f90:978]: I thins iulog is 6, so fluxh(iulog)??

**Review by nmizukami — COMMENTED** [review]
Thank you Erik to clean up the codes and fixing lot of things.   Overall looks good to me.

A couple of things to change are 

1.  remove line 210 in ascii_utils.f90 (I believe this can be removed)
2. if it is safe to remove the module variables in RtmTimeManager.F90, they should be removed.
 
I guess it is ok to leave freeDecomp commented out for now (maybe we can ask Jim why this does not work?)

File: cime_config/buildnml (hunk 5 above)
Comment (nmizukami) [reply cime_config/buildnml:328]: make sense that windows machine is not work if use string concatenation including `/` (windows use `\` instead of `/`)

File: route/build/src/mpi_utils.f90 (hunk 6 above)
Comment (ekluzek) [reply route/build/src/mpi_utils.f90:978]: OK, got this.

File: route/build/cpl/RtmTimeManager.F90 [hunk 7]
```diff
@@ -20,14 +19,14 @@ MODULE RtmTimeManager
   !--------------------------------------------------------------------------
 
   ! Input from CESM driver
-  integer,  save      :: nelapse               = integerMissing, & ! number of timesteps (or days if negative) to extend a run
+  integer             :: nelapse               = integerMissing, & ! number of timesteps (or days if negative) to extend a run
```
[the remark this answers is not in the document]
Comment (ekluzek) [reply route/build/cpl/RtmTimeManager.F90:22]: OK, just removing them.

File: route/build/src/ascii_utils.f90 (hunk 4 above)
Comment (ekluzek) [reply route/build/src/ascii_utils.f90:210]: OK

**Review by nmizukami — COMMENTED** [review]
One comment is about pio_freedecomp input argument

File: route/build/src/pio_utils.f90 [hunk 8]
```diff
@@ -354,16 +366,16 @@ SUBROUTINE closeFile(pioFileDesc, fileOpen)
   END SUBROUTINE closeFile
 
   !-----------------------------------------------------------------------
-  SUBROUTINE freeDecomp(pioFileDesc, iodesc)
+  SUBROUTINE freeDecomp(pioIOsystem, iodesc)
```
[the remark this answers is not in the document]
Comment (ekluzek) [reply route/build/src/pio_utils.f90:369]: The thing is that using pioFileDesc wasn't working with the nag compiler. So I'd say we should only use pioIOsystem. It's possible there's a bug in using pioFileDesc -- just for this version of PIO though. But, since this is working with pioSystem, I'd say just use it.

[the remark this answers is not in the document]
Comment (nmizukami) [reply route/build/src/pio_utils.f90:369]: Ok, if it working as expected, i would say ok.  So CLM also uses pioSystem??

File: route/build/src/write_restart_pio.f90 [hunk 9]
```diff
@@ -959,37 +982,37 @@ SUBROUTINE write_state_nc(fname,                &   ! Input: state netcdf name
  call write_history_state(ierr, cmessage)
  if(ierr/=0)then; message=trim(message)//trim(cmessage); return; endif
 
+ ! close netCDF
+ call closeFile(pioFileDescState, restartOpen)
+
  ! clean decomposition data
```
[the remark this answers is not in the document]
Comment (ekluzek) [reply route/build/src/write_restart_pio.f90:988]: My bet is that the pio File descriptor option, actually then points to the pioSystem that's associated with the pioFileDesc. One problem is if the pioFileDesc is freed before you do that. I also had problems with the Nag compiler if you didn't close pioFileDesc, before doing the decomp free.  Which just tells me in this case we should always use pioSystem. We could bring this up with Jim, but since we have it working I'm not sure how important it is. But, certainly not bad to do...

File: route/build/src/write_simoutput_pio.f90 [hunk 10]
```diff
@@ -108,8 +108,8 @@ SUBROUTINE main_new_file(ierr, message)
     end if
 
     ! update history files
```
[the remark this answers is not in the document]
Comment (ekluzek) [reply route/build/src/write_simoutput_pio.f90:110]: Oh, yes, I'll remove that.

[the remark this answers is not in the document]
Comment (ekluzek) [reply route/build/src/write_simoutput_pio.f90]: OK, got it.

File: route/build/src/pio_utils.f90 (hunk 8 above)
[the remark this answers is not in the document]
Comment (ekluzek) [reply route/build/src/pio_utils.f90:369]: I checked to see what CTSM is doing. It looks like it creates an array of io_desc_t types for the different dimensions and such it needs. But, it never free's the memory for them. So it's creating them once at initialization and not bothering to free them. I added issue #409 to talk about doing that in mizuRoute as well.

[the remark this answers is not in the document]
Comment (nmizukami) [reply route/build/src/pio_utils.f90:369]: I see.  so this can avoid memory leak from create/destroy repeat for each history file.   so one time initialization of pio decomposition would be way to go.

**Comment by nmizukami** [comment]
I don't think i have any other comments so if this works as expected. I could merge it.

**Comment by ekluzek** [comment]
I'm not quite ready yet. I'm having trouble with ERI tests which currently fail, so I'm trying to figure out why and see if I can fix it. The files it expects to compare just aren't there for mizuRoute. I'll let you know when I have that working and have replicated running the test suite on cheyenne and izumi.

**Comment by ekluzek** [comment]
OK, this is ready to be merged.

**Comment by ekluzek** [comment]
The tests on cheyenne and izumi are all working as expected.

Izumi:


================================================================================
These tests passed
================================================================================
PET_Mmpi-serial_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_intel.mizuroute-default
SMS_D.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_intel.mizuroute-default
SMS_D.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default
SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_gnu.mizuroute-default
SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_intel.mizuroute-default
SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default
================================================================================
================================================================================
These tests failed
================================================================================
ERI_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_gnu.mizuroute-default     COMPARE_base_hybrid COMPARE_base_rest EXPECTED
ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default    COMPARE_base_rest             EXPECTED

cheyenne:

================================================================================
These tests passed
================================================================================
ERI.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
ERI_PS.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
ERS.f09_f09_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
ERS_PS.f19_f19_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
ERS_PS.f19_f19_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
ERS_PS.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
ERS_PS.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
ERS_PS.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
ERS_PS.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
ERS_PS.nldas2_nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
ERS_PS.nldas2_nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
PET_Mmpi-serial_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
PET_Mmpi-serial_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
PET_P215x8.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
PET_P215x8.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
PFS.f19_f19_rHDMA_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
PFS.f19_f19_rHDMA_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
SMS.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
SMS.f09_f09_rMERIT_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-MERIT
SMS.f19_f19_rMERIT_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-MERIT
SMS.f19_f19_rMERIT_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-MERIT
SMS_D.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
SMS_D.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
SMS_D.nldas2_nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
SMS_Mmpi-serial_D_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
SMS_Mmpi-serial_D_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
SMS_P720x4.nldas2_nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default
SMS_P720x4.nldas2_nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
SMS_P80x18.f19_f19_rMERIT_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-MERIT
SMS_PS.hcru_hcru_mt13.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-hcru
SMS_PS.hcru_hcru_rHDMAlk_mt13.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-hcru
================================================================================
================================================================================
These tests failed
================================================================================
ERI_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default         COMPARE_base_hybrid COMPARE_base_rest        EXPECTED
ERP_D_Mmpi-serial_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default         COMPARE_base_rest             EXPECTED
ERS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default       COMPARE_base_rest             EXPECTED
ERS_D_Mmpi-serial_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default         COMPARE_base_rest             EXPECTED
SMS_D.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-5x5_amazon_rHDMA        RUN           EXPECTED

**Comment by nmizukami** [comment]
Hi Erik (@ekluzek),
I closed all the issues mentioned in the comments, but wonder if these issues can be also closed? 

#283
#344
#386
#388 (this may be still open to discussion)
#404
